ARG CPU_BASE_IMAGE=docker.io/maponyacharles/sceptreai:training-cpu-0.1.4
FROM ${CPU_BASE_IMAGE}

USER root
RUN apt-get update \
    && apt-get install --no-install-recommends --yes mesa-opencl-icd ocl-icd-libopencl1 \
    && rm -rf /var/lib/apt/lists/*
USER 10001

ENV AUTOML_INTEL_OPENCL_AVAILABLE=1
CMD ["python", "-m", "automl_api.training.worker", "--help"]
