"""phase1 durable workflow state

Revision ID: 0005_phase1_durable_workflows
Revises: 0004_resumable_dataset_uploads
Create Date: 2026-08-13 14:44:36.109927
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0005_phase1_durable_workflows"
down_revision = "0004_resumable_dataset_uploads"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "final_test_allocations",
        sa.Column("split_digest", sa.String(length=128), nullable=False),
        sa.Column("project_reference", sa.String(length=255), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_provider", sa.String(length=32), nullable=False),
        sa.Column("provider_manifest_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "allocated",
                "opened",
                "committed",
                "failed",
                name="final_test_status",
                native_enum=False,
            ),
            server_default="allocated",
            nullable=False,
        ),
        sa.Column("cas_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_digest", sa.String(length=128), nullable=True),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_final_test_allocations")),
        sa.UniqueConstraint("scope_id", name="uq_final_test_scope"),
        sa.UniqueConstraint("split_digest", name="uq_final_test_split_digest"),
    )
    op.create_index(
        "ix_final_test_status", "final_test_allocations", ["status", "updated_at"], unique=False
    )
    op.create_table(
        "final_test_authority_receipts",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("request_digest", sa.String(length=128), nullable=False),
        sa.Column("receipt_digest", sa.String(length=128), nullable=False),
        sa.Column("signature_algorithm", sa.String(length=32), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["final_test_allocations.id"],
            name=op.f("fk_final_test_authority_receipts_allocation_id_final_test_allocations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_final_test_authority_receipts")),
        sa.UniqueConstraint("allocation_id", "operation", name="uq_final_test_receipt_operation"),
        sa.UniqueConstraint("receipt_digest", name="uq_final_test_receipt_digest"),
    )
    op.create_table(
        "deletion_tombstones",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("legal_hold", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_deletion_tombstones_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_deletion_tombstones_requested_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_tombstones")),
        sa.UniqueConstraint("project_id", "id", name="uq_deletion_tombstones_project_id_id"),
        sa.UniqueConstraint("project_id", "resource_type", "resource_id", name="uq_tombstone"),
    )
    op.create_index(
        "ix_tombstone_status",
        "deletion_tombstones",
        ["project_id", "status", "requested_at"],
        unique=False,
    )
    op.create_table(
        "digest_verifications",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("expected_digest", sa.String(length=128), nullable=False),
        sa.Column("observed_digest", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quarantined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_digest_verifications_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_digest_verifications")),
        sa.UniqueConstraint(
            "project_id",
            "resource_type",
            "resource_id",
            "digest_scope",
            name="uq_digest_verification_resource",
        ),
    )
    op.create_index(
        "ix_digest_verification_status",
        "digest_verifications",
        ["project_id", "status"],
        unique=False,
    )
    op.create_table(
        "estimator_catalog_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("release_version", sa.String(length=64), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_estimator_catalog_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_estimator_catalog_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_estimator_catalogs_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_estimator_catalog_revision"),
    )
    op.create_table(
        "feature_contract_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("target_column", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_feature_contract_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_contract_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_feature_contracts_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_feature_contract_revision"),
    )
    op.create_table(
        "feature_registry_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_feature_registry_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_registry_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_feature_registries_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_feature_registry_revision"),
    )
    op.create_table(
        "feature_search_space_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("metric_name", sa.String(length=160), nullable=False),
        sa.Column("metric_direction", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_feature_search_space_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_search_space_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_search_spaces_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_search_space_revision"),
    )
    op.create_table(
        "provider_conformance_campaigns",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_key", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("profile_digest", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_provider_conformance_campaigns_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_conformance_campaigns")),
        sa.UniqueConstraint("project_id", "campaign_key", name="uq_conformance_campaign_key"),
        sa.UniqueConstraint("project_id", "id", name="uq_conformance_campaigns_project_id_id"),
    )
    op.create_table(
        "workflow_commands",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "request_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="command_status",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=80), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column(
            "response_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_retries", sa.Integer(), server_default="5", nullable=False),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("replayed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "retry_count >= 0 AND max_retries >= 0",
            name=op.f("ck_workflow_commands_command_retry_bounds"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_workflow_commands_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workflow_commands_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replayed_by"], ["users.id"], name=op.f("fk_workflow_commands_replayed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_commands")),
        sa.UniqueConstraint("project_id", "id", name="uq_workflow_commands_project_id_id"),
        sa.UniqueConstraint(
            "project_id", "operation", "idempotency_key", name="uq_command_idempotency"
        ),
    )
    op.create_index(
        "ix_workflow_commands_status_available",
        "workflow_commands",
        ["status", "available_at"],
        unique=False,
    )
    op.create_table(
        "capacity_reservations",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("resource_class", sa.String(length=80), nullable=False),
        sa.Column("cpu_millis", sa.BigInteger(), nullable=False),
        sa.Column("memory_bytes", sa.BigInteger(), nullable=False),
        sa.Column("gpu_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cpu_millis >= 0 AND memory_bytes >= 0 AND gpu_count >= 0",
            name=op.f("ck_capacity_reservations_capacity_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "command_id"],
            ["workflow_commands.project_id", "workflow_commands.id"],
            name="fk_capacity_command_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_capacity_reservations_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_capacity_reservations")),
        sa.UniqueConstraint("project_id", "command_id", name="uq_capacity_command"),
    )
    op.create_index(
        "ix_capacity_project_expires",
        "capacity_reservations",
        ["project_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "deletion_stages",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("tombstone_id", sa.Uuid(), nullable=False),
        sa.Column("resource_class", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("replayed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "tombstone_id"],
            ["deletion_tombstones.project_id", "deletion_tombstones.id"],
            name="fk_deletion_stage_tombstone_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_deletion_stages_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replayed_by"], ["users.id"], name=op.f("fk_deletion_stages_replayed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deletion_stages")),
        sa.UniqueConstraint("tombstone_id", "resource_class", name="uq_deletion_stage_class"),
    )
    op.create_index(
        "ix_deletion_stage_claim", "deletion_stages", ["status", "lease_expires_at"], unique=False
    )
    op.create_table(
        "feature_recipe_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("registry_revision_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "registry_revision_id"],
            ["feature_registry_revisions.project_id", "feature_registry_revisions.id"],
            name="fk_recipe_registry_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_feature_recipe_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_recipe_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_feature_recipes_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_feature_recipe_revision"),
    )
    op.create_table(
        "outbox_entries",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.Uuid(), nullable=False),
        sa.Column("event_key", sa.String(length=255), nullable=False),
        sa.Column("topic", sa.String(length=160), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "claimed", "delivered", "dead", name="outbox_status", native_enum=False
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivery_attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_attempts >= 0", name=op.f("ck_outbox_entries_outbox_delivery_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "command_id"],
            ["workflow_commands.project_id", "workflow_commands.id"],
            name="fk_outbox_command_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_outbox_entries_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_entries")),
        sa.UniqueConstraint("project_id", "event_key", name="uq_outbox_event_key"),
    )
    op.create_index(
        "ix_outbox_status_available", "outbox_entries", ["status", "available_at"], unique=False
    )
    op.create_table(
        "dataset_split_revisions",
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("train_digest", sa.String(length=128), nullable=False),
        sa.Column("validation_digest", sa.String(length=128), nullable=False),
        sa.Column("final_test_digest", sa.String(length=128), nullable=False),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "dataset_version_id"],
            ["dataset_versions.project_id", "dataset_versions.id"],
            name="fk_split_dataset_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_dataset_split_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_split_revisions")),
        sa.UniqueConstraint(
            "project_id", "dataset_version_id", "revision", name="uq_split_revision"
        ),
        sa.UniqueConstraint("project_id", "id", name="uq_split_revisions_project_id_id"),
    )
    op.create_table(
        "prepared_artifacts",
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("object_uri", sa.String(length=1024), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "dataset_version_id"],
            ["dataset_versions.project_id", "dataset_versions.id"],
            name="fk_prepared_artifact_dataset_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_prepared_artifacts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prepared_artifacts")),
        sa.UniqueConstraint(
            "project_id", "dataset_version_id", "revision", name="uq_prepared_artifact_revision"
        ),
        sa.UniqueConstraint("project_id", "id", name="uq_prepared_artifacts_project_id_id"),
    )
    op.create_table(
        "promotional_scopes",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scope_key", sa.String(length=255), nullable=False),
        sa.Column("split_revision_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_provider", sa.String(length=32), nullable=False),
        sa.Column("expected_members", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "sealed",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="scope_status",
                native_enum=False,
            ),
            server_default="open",
            nullable=False,
        ),
        sa.Column("membership_digest", sa.String(length=128), nullable=True),
        sa.Column("sealed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cas_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expected_members > 0",
            name=op.f("ck_promotional_scopes_scope_expected_members_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "split_revision_id"],
            ["dataset_split_revisions.project_id", "dataset_split_revisions.id"],
            name="fk_scope_split_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_promotional_scopes_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotional_scopes")),
        sa.UniqueConstraint("project_id", "id", name="uq_promotional_scopes_project_id_id"),
        sa.UniqueConstraint("project_id", "scope_key", name="uq_promotional_scope_key"),
    )
    op.create_table(
        "training_candidates",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("model_run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_key", sa.String(length=255), nullable=False),
        sa.Column("estimator_key", sa.String(length=160), nullable=False),
        sa.Column("catalog_revision_id", sa.Uuid(), nullable=False),
        sa.Column("feature_recipe_revision_id", sa.Uuid(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "catalog_revision_id"],
            ["estimator_catalog_revisions.project_id", "estimator_catalog_revisions.id"],
            name="fk_candidate_catalog_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "feature_recipe_revision_id"],
            ["feature_recipe_revisions.project_id", "feature_recipe_revisions.id"],
            name="fk_candidate_recipe_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "model_run_id"],
            ["model_runs.project_id", "model_runs.id"],
            name="fk_candidate_run_project",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_candidates")),
        sa.UniqueConstraint("model_run_id", "candidate_key", name="uq_candidate_run_key"),
        sa.UniqueConstraint("project_id", "id", name="uq_training_candidates_project_id_id"),
    )
    op.create_table(
        "promotional_scope_members",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("model_run_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "model_run_id"],
            ["model_runs.project_id", "model_runs.id"],
            name="fk_scope_member_run_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "scope_id"],
            ["promotional_scopes.project_id", "promotional_scopes.id"],
            name="fk_scope_member_scope_project",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promotional_scope_members")),
        sa.UniqueConstraint("scope_id", "model_run_id", name="uq_scope_member_run"),
    )
    op.create_table(
        "training_trials",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_id", sa.Uuid(), nullable=False),
        sa.Column("suggestion_id", sa.String(length=255), nullable=False),
        sa.Column("params_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result_digest", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "candidate_id"],
            ["training_candidates.project_id", "training_candidates.id"],
            name="fk_trial_candidate_project",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_trials")),
        sa.UniqueConstraint("candidate_id", "suggestion_id", name="uq_trial_suggestion"),
        sa.UniqueConstraint("project_id", "id", name="uq_training_trials_project_id_id"),
    )
    op.create_table(
        "workflow_attempts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "splitter",
                "preparation",
                "training_run",
                "training_trial",
                "champion_refit",
                "champion_evaluation",
                "provider_conformance",
                name="workflow_stage",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("logical_key", sa.String(length=255), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=True),
        sa.Column("model_run_id", sa.Uuid(), nullable=True),
        sa.Column("trial_id", sa.Uuid(), nullable=True),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("conformance_campaign_id", sa.Uuid(), nullable=True),
        sa.Column("workload_identity", sa.String(length=255), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.String(length=128), nullable=False),
        sa.Column("predecessor_attempt_id", sa.Uuid(), nullable=True),
        sa.Column(
            "predecessor_checkpoint_allowlist",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "claimed",
                "submitted",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                "superseded",
                name="attempt_status",
                native_enum=False,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("ray_job_name", sa.String(length=255), nullable=True),
        sa.Column("ray_cluster_name", sa.String(length=255), nullable=True),
        sa.Column("ray_submission_id", sa.String(length=255), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=255), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retry_budget", sa.Integer(), server_default="5", nullable=False),
        sa.Column("checkpoint_uri", sa.String(length=1024), nullable=True),
        sa.Column("terminal_reason", sa.Text(), nullable=True),
        sa.Column("terminal_cas_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("cleanup_state", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column("replayed_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(stage = 'training_run' AND model_run_id IS NOT NULL "
            "AND trial_id IS NULL AND scope_id IS NULL "
            "AND conformance_campaign_id IS NULL) OR "
            "(stage = 'training_trial' AND model_run_id IS NOT NULL "
            "AND trial_id IS NOT NULL AND scope_id IS NULL "
            "AND conformance_campaign_id IS NULL) OR "
            "(stage IN ('splitter', 'preparation') "
            "AND dataset_version_id IS NOT NULL AND model_run_id IS NULL "
            "AND trial_id IS NULL AND scope_id IS NULL "
            "AND conformance_campaign_id IS NULL) OR "
            "(stage IN ('champion_refit', 'champion_evaluation') "
            "AND scope_id IS NOT NULL AND trial_id IS NULL "
            "AND conformance_campaign_id IS NULL) OR "
            "(stage = 'provider_conformance' "
            "AND conformance_campaign_id IS NOT NULL "
            "AND model_run_id IS NULL AND trial_id IS NULL "
            "AND scope_id IS NULL)",
            name=op.f("ck_workflow_attempts_attempt_typed_parent"),
        ),
        sa.CheckConstraint(
            "generation > 0 AND retry_count >= 0",
            name=op.f("ck_workflow_attempts_attempt_generation_retry"),
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_attempt_id"],
            ["workflow_attempts.id"],
            name=op.f("fk_workflow_attempts_predecessor_attempt_id_workflow_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "conformance_campaign_id"],
            ["provider_conformance_campaigns.project_id", "provider_conformance_campaigns.id"],
            name="fk_attempt_conformance_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "dataset_version_id"],
            ["dataset_versions.project_id", "dataset_versions.id"],
            name="fk_attempt_dataset_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "model_run_id"],
            ["model_runs.project_id", "model_runs.id"],
            name="fk_attempt_run_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "scope_id"],
            ["promotional_scopes.project_id", "promotional_scopes.id"],
            name="fk_attempt_scope_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "trial_id"],
            ["training_trials.project_id", "training_trials.id"],
            name="fk_attempt_trial_project",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workflow_attempts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["replayed_by"], ["users.id"], name=op.f("fk_workflow_attempts_replayed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_attempts")),
        sa.UniqueConstraint("fencing_token", name=op.f("uq_workflow_attempts_fencing_token")),
        sa.UniqueConstraint("project_id", "id", name="uq_workflow_attempts_project_id_id"),
        sa.UniqueConstraint(
            "project_id", "logical_key", "generation", name="uq_attempt_generation"
        ),
    )
    op.create_index(
        "ix_attempt_claim",
        "workflow_attempts",
        ["status", "available_at", "lease_expires_at"],
        unique=False,
    )
    op.create_table(
        "workflow_checkpoints",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("object_uri", sa.String(length=1024), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column("event_sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "attempt_id"],
            ["workflow_attempts.project_id", "workflow_attempts.id"],
            name="fk_checkpoint_attempt_project",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_checkpoints")),
        sa.UniqueConstraint("attempt_id", "sequence", name="uq_checkpoint_sequence"),
    )
    op.create_table(
        "workflow_events",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("result_digest", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "attempt_id"],
            ["workflow_attempts.project_id", "workflow_attempts.id"],
            name="fk_event_attempt_project",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_events")),
        sa.UniqueConstraint("attempt_id", "event_key", name="uq_workflow_event_key"),
        sa.UniqueConstraint("attempt_id", "sequence", name="uq_workflow_event_sequence"),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column(
            "digest_algorithm", sa.String(length=32), server_default="sha256", nullable=False
        ),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column(
            "digest_scope",
            sa.String(length=80),
            server_default="multipart_manifest",
            nullable=False,
        ),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column("expected_object_digest", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column("observed_object_digest", sa.String(length=128), nullable=True),
    )
    op.add_column(
        "dataset_upload_sessions", sa.Column("quarantine_reason", sa.Text(), nullable=True)
    )
    op.add_column(
        "dataset_upload_sessions", sa.Column("lease_owner", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "dataset_upload_sessions",
        sa.Column("retry_budget", sa.Integer(), server_default="5", nullable=False),
    )
    op.add_column("dataset_upload_sessions", sa.Column("terminal_reason", sa.Text(), nullable=True))
    op.add_column("dataset_upload_sessions", sa.Column("replayed_by", sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE dataset_upload_sessions "
        "SET quarantine_reason = 'legacy_digest_scope_requires_object_verification', "
        "terminal_reason = 'legacy upload hash retained as multipart manifest' "
        "WHERE dataset_version_id IS NULL OR status <> 'completed'"
    )
    op.create_foreign_key(
        op.f("fk_dataset_upload_sessions_replayed_by_users"),
        "dataset_upload_sessions",
        "users",
        ["replayed_by"],
        ["id"],
    )
    op.alter_column(
        "run_artifacts",
        "byte_size",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "run_artifacts",
        "byte_size",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.drop_constraint(
        op.f("fk_dataset_upload_sessions_replayed_by_users"),
        "dataset_upload_sessions",
        type_="foreignkey",
    )
    op.drop_column("dataset_upload_sessions", "replayed_by")
    op.drop_column("dataset_upload_sessions", "terminal_reason")
    op.drop_column("dataset_upload_sessions", "retry_budget")
    op.drop_column("dataset_upload_sessions", "retry_count")
    op.drop_column("dataset_upload_sessions", "heartbeat_at")
    op.drop_column("dataset_upload_sessions", "lease_expires_at")
    op.drop_column("dataset_upload_sessions", "lease_owner")
    op.drop_column("dataset_upload_sessions", "quarantine_reason")
    op.drop_column("dataset_upload_sessions", "observed_object_digest")
    op.drop_column("dataset_upload_sessions", "expected_object_digest")
    op.drop_column("dataset_upload_sessions", "digest_scope")
    op.drop_column("dataset_upload_sessions", "digest_algorithm")
    op.drop_table("workflow_events")
    op.drop_table("workflow_checkpoints")
    op.drop_index("ix_attempt_claim", table_name="workflow_attempts")
    op.drop_table("workflow_attempts")
    op.drop_table("training_trials")
    op.drop_table("promotional_scope_members")
    op.drop_table("training_candidates")
    op.drop_table("promotional_scopes")
    op.drop_table("prepared_artifacts")
    op.drop_table("dataset_split_revisions")
    op.drop_index("ix_outbox_status_available", table_name="outbox_entries")
    op.drop_table("outbox_entries")
    op.drop_table("feature_recipe_revisions")
    op.drop_index("ix_deletion_stage_claim", table_name="deletion_stages")
    op.drop_table("deletion_stages")
    op.drop_index("ix_capacity_project_expires", table_name="capacity_reservations")
    op.drop_table("capacity_reservations")
    op.drop_index("ix_workflow_commands_status_available", table_name="workflow_commands")
    op.drop_table("workflow_commands")
    op.drop_table("provider_conformance_campaigns")
    op.drop_table("feature_search_space_revisions")
    op.drop_table("feature_registry_revisions")
    op.drop_table("feature_contract_revisions")
    op.drop_table("estimator_catalog_revisions")
    op.drop_index("ix_digest_verification_status", table_name="digest_verifications")
    op.drop_table("digest_verifications")
    op.drop_index("ix_tombstone_status", table_name="deletion_tombstones")
    op.drop_table("deletion_tombstones")
    op.drop_table("final_test_authority_receipts")
    op.drop_index("ix_final_test_status", table_name="final_test_allocations")
    op.drop_table("final_test_allocations")
    # ### end Alembic commands ###
