"""phase1 public contract revisions

Revision ID: 0006_phase1_public_contracts
Revises: 0005_phase1_durable_workflows
Create Date: 2026-08-13 14:57:54.432798
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0006_phase1_public_contracts"
down_revision = "0005_phase1_durable_workflows"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_objective_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("metric_name", sa.String(length=160), nullable=False),
        sa.Column("metric_direction", sa.String(length=16), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_search_objective_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_objective_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_search_objectives_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_search_objective_revision"),
    )
    op.create_table(
        "experiment_spec_revisions",
        sa.Column("name", sa.String(length=220), nullable=False),
        sa.Column("dataset_version_id", sa.Uuid(), nullable=False),
        sa.Column("split_revision_id", sa.Uuid(), nullable=False),
        sa.Column("feature_contract_revision_id", sa.Uuid(), nullable=False),
        sa.Column("feature_search_space_revision_id", sa.Uuid(), nullable=False),
        sa.Column("search_objective_revision_id", sa.Uuid(), nullable=False),
        sa.Column("catalog_revision_id", sa.Uuid(), nullable=False),
        sa.Column("task_type", sa.String(length=32), nullable=False),
        sa.Column("target_column", sa.String(length=255), nullable=True),
        sa.Column("primary_metric", sa.String(length=160), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("digest_algorithm", sa.String(length=32), nullable=False),
        sa.Column("digest_scope", sa.String(length=80), nullable=False),
        sa.Column("content_digest", sa.String(length=128), nullable=False),
        sa.Column(
            "specification",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "catalog_revision_id"],
            ["estimator_catalog_revisions.project_id", "estimator_catalog_revisions.id"],
            name="fk_experiment_catalog_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "dataset_version_id"],
            ["dataset_versions.project_id", "dataset_versions.id"],
            name="fk_experiment_dataset_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "feature_contract_revision_id"],
            ["feature_contract_revisions.project_id", "feature_contract_revisions.id"],
            name="fk_experiment_contract_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "feature_search_space_revision_id"],
            ["feature_search_space_revisions.project_id", "feature_search_space_revisions.id"],
            name="fk_experiment_search_space_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "search_objective_revision_id"],
            ["search_objective_revisions.project_id", "search_objective_revisions.id"],
            name="fk_experiment_objective_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "split_revision_id"],
            ["dataset_split_revisions.project_id", "dataset_split_revisions.id"],
            name="fk_experiment_split_project",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_experiment_spec_revisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_spec_revisions")),
        sa.UniqueConstraint("project_id", "id", name="uq_experiment_specs_project_id_id"),
        sa.UniqueConstraint("project_id", "name", "revision", name="uq_experiment_spec_revision"),
    )
    op.add_column(
        "promotional_scopes",
        sa.Column("mode", sa.String(length=32), server_default="validation_only", nullable=False),
    )
    op.add_column(
        "promotional_scopes", sa.Column("experiment_spec_revision_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "promotional_scopes",
        sa.Column("membership_deadline_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "promotional_scopes",
        sa.Column("scope_started_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "promotional_scopes",
        sa.Column("scope_deadline_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "promotional_scopes",
        sa.Column(
            "comparison_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "promotional_scopes",
        sa.Column("final_threshold_revision", sa.String(length=128), nullable=True),
    )
    op.create_foreign_key(
        "fk_scope_experiment_project",
        "promotional_scopes",
        "experiment_spec_revisions",
        ["project_id", "experiment_spec_revision_id"],
        ["project_id", "id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_scope_experiment_project", "promotional_scopes", type_="foreignkey")
    op.drop_column("promotional_scopes", "final_threshold_revision")
    op.drop_column("promotional_scopes", "comparison_policy")
    op.drop_column("promotional_scopes", "scope_deadline_at")
    op.drop_column("promotional_scopes", "scope_started_at")
    op.drop_column("promotional_scopes", "membership_deadline_at")
    op.drop_column("promotional_scopes", "experiment_spec_revision_id")
    op.drop_column("promotional_scopes", "mode")
    op.drop_table("experiment_spec_revisions")
    op.drop_table("search_objective_revisions")
    # ### end Alembic commands ###
