# MicroK8s pulls the public Sceptre images from Docker Hub.
api:
  image: {pullPolicy: IfNotPresent}
ui:
  image: {pullPolicy: IfNotPresent}
mlflow:
  image: {pullPolicy: IfNotPresent}
training:
  imagePullPolicy: IfNotPresent
inference:
  image: {pullPolicy: IfNotPresent}
environment: local
