apiVersion: v1
kind: ConfigMap
metadata:
  name: automl-platform-config
  namespace: automl
data:
  OBJECT_STORE_TYPE: minio
  DATASET_CACHE_SIZE_GB: "5"
  GPU_ENABLED: "true"
  MAX_CLUSTER_CPU_PERCENT: "70"
  MAX_NODE_AVAILABLE_FRACTION_PER_JOB: "1.0"
  MAX_CONCURRENT_JOBS: "2"
  MLFLOW_TRACKING_URI: http://automl-mlflow:5000
  TRAINING_NAMESPACE: automl
  TRAINING_IMAGE: automl-training:local
  INFERENCE_IMAGE: automl-inference:local
  INFERENCE_SERVICE_ACCOUNT: default
  INFERENCE_SERVICE_TYPE: NodePort
  TRAINING_ACTIVE_DEADLINE_SECONDS: "21600"
  TRAINING_MAX_ACTIVE_DEADLINE_SECONDS: "86400"
  TRAINING_DEADLINE_MULTIPLIER: "6"
