apiVersion: v1
kind: Service
metadata:
  name: automl-minio
  namespace: automl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: automl-minio
  ports:
    - name: api
      port: 9000
      targetPort: api
    - name: console
      port: 9001
      targetPort: console
