apiVersion: v1
kind: Service
metadata:
  name: automl-postgres
  namespace: automl
spec:
  selector:
    app.kubernetes.io/name: automl-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
