apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sceptre.apiServiceAccount" . }}
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sceptre.trainingServiceAccount" . }}
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sceptre.inferenceServiceAccount" . }}
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sceptre.fullname" . }}-workloads
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "persistentvolumeclaims", "resourcequotas"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ include "sceptre.platformSecretName" . }}
      - {{ include "sceptre.objectStoreSecretName" . }}
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete"]
  {{- if .Values.inference.ingress.enabled }}
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "delete"]
  {{- end }}
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sceptre.fullname" . }}-workloads
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sceptre.apiServiceAccount" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sceptre.fullname" . }}-workloads
{{- if .Values.capabilities.clusterObserver.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sceptre.fullname" . }}-observer
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: ["scheduling.k8s.io"]
    resources: ["priorityclasses"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sceptre.fullname" . }}-observer
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sceptre.apiServiceAccount" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sceptre.fullname" . }}-observer
{{- end }}
