{{- if not .Values.platform.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sceptre.platformSecretName" . }}
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "sceptre.databaseUrl" . | quote }}
  MLFLOW_DATABASE_URL: {{ include "sceptre.mlflowDatabaseUrl" . | quote }}
---
{{- end }}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sceptre.authSecretName" . }}
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.auth.jwtSecret | quote }}
  {{ .Values.auth.passwordResetEmail.usernameKey }}: {{ .Values.auth.passwordResetEmail.username | quote }}
  {{ .Values.auth.passwordResetEmail.passwordKey }}: {{ .Values.auth.passwordResetEmail.password | quote }}
---
{{- end }}
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sceptre.fullname" . }}-postgresql
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
---
{{- end }}
{{- if and .Values.seaweedfs.enabled (not .Values.seaweedfs.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sceptre.objectStoreSecretName" . }}
  labels:
    {{- include "sceptre.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.seaweedfs.auth.accessKeyKey }}: {{ .Values.seaweedfs.auth.accessKey | quote }}
  {{ .Values.seaweedfs.auth.secretKeyKey }}: {{ .Values.seaweedfs.auth.secretKey | quote }}
{{- end }}
