import { expect, test } from "@playwright/test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

test("workspace navigation, project dialogs, and account forms remain accessible", async ({ page, isMobile }, testInfo) => {
  test.skip(!process.env.LIVE_RECOVERY, "requires the populated local workspace");
  test.setTimeout(5 * 60_000);
  const state = JSON.parse(readFileSync(join(process.env.RECOVERY_STATE_DIR!, "browser-state.json"), "utf8"));
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const fits = async () => expect.poll(() => page.evaluate(() =>
    document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true);
  await page.goto("/auth");
  await expect(page.getByRole("button", { name: "Sign in", exact: true })).toBeVisible();
  await fits();
  await page.screenshot({ path: testInfo.outputPath("auth.png") });
  await page.getByLabel("Work email", { exact: true }).fill(state.email);
  await page.getByLabel("Password", { exact: true }).fill(state.password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/projects$/);
  const search = page.getByRole("textbox", { name: "Search projects" });
  await search.fill("no-project-matches-this-search");
  await expect(page.getByRole("heading", { name: "No matching projects" })).toBeVisible();
  await search.fill("");
  await page.getByRole("button", { name: "New project", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Create a project" });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel("Project name", { exact: true }).fill("Visual review — unsaved");
  await fits();
  await page.screenshot({ path: testInfo.outputPath("project-dialog.png") });
  await page.keyboard.press("Escape");
  await expect(dialog).toBeHidden();
  await expect(page.getByRole("button", { name: "New project", exact: true })).toBeFocused();
  await page.goto(state.projectUrl);
  await expect(page.getByRole("navigation", { name: "Model journey" })).toBeVisible();
  if (isMobile) await page.getByRole("button", { name: "Open menu", exact: true }).click();
  const navigation = page.getByRole("navigation", { name: "Project navigation" });
  await expect(navigation.getByRole("link", { name: "Overview", exact: true })).toHaveAttribute("aria-current", "page");
  await page.screenshot({ path: testInfo.outputPath("navigation.png") });
  await navigation.getByRole("link", { name: "Team", exact: true }).click();
  await expect(page.locator("main h1")).toBeVisible();
  await fits();
  await page.screenshot({ path: testInfo.outputPath("team.png") });
  await page.getByRole("link", { name: "Workspace settings", exact: true }).click();
  await expect(page).toHaveURL(/\/settings$/);
  await expect(page.locator("main h1")).toBeVisible();
  await fits();
  await page.screenshot({ path: testInfo.outputPath("settings.png") });
  await page.getByRole("link", { name: "My account", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Personal details" })).toBeVisible();
  await expect(page.getByLabel("Email address", { exact: true })).toHaveValue(state.email);
  await expect(page.getByRole("button", { name: "Save profile", exact: true })).toBeVisible();
  await fits();
  await page.screenshot({ path: testInfo.outputPath("account.png") });
  if (isMobile) await page.getByRole("button", { name: "Open menu", exact: true }).click();
  await page.getByRole("link", { name: "Governance dashboard", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Governance dashboard", exact: true })).toBeVisible();
  await fits();
  await page.screenshot({ path: testInfo.outputPath("governance.png") });
  expect(errors).toEqual([]);
});
